export const autonomousLeft = () => {
  return (
    <svg
      width='120'
      height='56'
      viewBox='0 0 142 56'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
    >
      <defs>
        <linearGradient id='spot' x1='0' y1='0' x2='0' y2='1'>
          <stop
            offset='0%'
            stopColor='var(--third-color)'
            stopOpacity='{0}'
          ></stop>
          <stop
            offset='100%'
            stopColor='var(--fourth-color)'
            stopOpacity='{1}'
          ></stop>
        </linearGradient>
      </defs>
      <rect
        opacity='0.4'
        x='26.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='36.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='46.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='56.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='66.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='76.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='86.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='96.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='106.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
    </svg>
  );
};

export const autonomousRight = () => {
  return (
    <svg
      width='120'
      height='56'
      viewBox='0 0 142 56'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
    >
      <defs>
        <linearGradient id='spot' x1='0' y1='0' x2='0' y2='1'>
          <stop
            offset='0%'
            stopColor='var(--third-color)'
            stopOpacity='{0}'
          ></stop>
          <stop
            offset='100%'
            stopColor='var(--fourth-color)'
            stopOpacity='{1}'
          ></stop>
        </linearGradient>
      </defs>
      <rect
        opacity='0.4'
        x='26.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='36.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='46.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='56.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='66.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='76.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='86.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='96.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='106.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
    </svg>
  );
};

export const autonomousCenter = () => {
  return (
    <svg
      width='120'
      height='56'
      viewBox='0 0 142 56'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
    >
      <defs>
        <linearGradient id='spot' x1='0' y1='0' x2='0' y2='1'>
          <stop
            offset='0%'
            stopColor='var(--third-color)'
            stopOpacity='{0}'
          ></stop>
          <stop
            offset='100%'
            stopColor='var(--fourth-color)'
            stopOpacity='{1}'
          ></stop>
        </linearGradient>
      </defs>
      <rect
        opacity='0.4'
        x='26.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='36.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='46.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='56.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='66.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='76.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='86.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='96.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='106.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
    </svg>
  );
};

export const curve = () => {
  return (
    <svg
      width='120'
      height='56'
      viewBox='0 0 142 56'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
    >
      <defs>
        <linearGradient id='normal' x1='0' y1='0' x2='0' y2='1'>
          <stop
            offset='0%'
            stopColor='var(--third-color)'
            stopOpacity='{0}'
          ></stop>
          <stop
            offset='100%'
            stopColor='var(--fourth-color)'
            stopOpacity='{1}'
          ></stop>
        </linearGradient>
      </defs>
      <rect
        opacity='0.2'
        x='26.5'
        y='47'
        width='9'
        height='1'
        rx='0.5'
        fill='url(#normal)'
      ></rect>
      <rect
        opacity='0.4'
        x='36.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#normal)'
      ></rect>
      <rect
        opacity='0.4'
        x='46.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#normal)'
      ></rect>
      <rect
        opacity='0.8'
        x='56.5'
        y='24'
        width='9'
        height='24'
        rx='2'
        fill='url(#normal)'
      ></rect>
      <rect
        x='66.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#normal)'
      ></rect>
      <rect
        opacity='0.8'
        x='76.5'
        y='24'
        width='9'
        height='24'
        rx='2'
        fill='url(#normal)'
      ></rect>
      <rect
        opacity='0.4'
        x='86.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#normal)'
      ></rect>
      <rect
        opacity='0.4'
        x='96.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#normal)'
      ></rect>
      <rect
        opacity='0.2'
        x='106.5'
        y='47'
        width='9'
        height='1'
        rx='0.5'
        fill='url(#normal)'
      ></rect>
    </svg>
  );
};

export const spot = () => {
  return (
    <svg
      width='120'
      height='56'
      viewBox='0 0 142 56'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
    >
      <defs>
        <linearGradient id='spot' x1='0' y1='0' x2='0' y2='1'>
          <stop
            offset='0%'
            stopColor='var(--third-color)'
            stopOpacity='{0}'
          ></stop>
          <stop
            offset='100%'
            stopColor='var(--fourth-color)'
            stopOpacity='{1}'
          ></stop>
        </linearGradient>
      </defs>
      <rect
        opacity='0.4'
        x='26.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='36.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='46.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='56.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='66.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        x='76.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='86.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='96.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
      <rect
        opacity='0.4'
        x='106.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#spot)'
      ></rect>
    </svg>
  );
};

export const wide = () => {
  return (
    <svg
      width='120'
      height='56'
      viewBox='0 0 142 56'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
    >
      <defs>
        <linearGradient id='max' x1='0' y1='0' x2='0' y2='1'>
          <stop
            offset='0%'
            stopColor='var(--third-color)'
            stopOpacity='{0}'
          ></stop>
          <stop
            offset='100%'
            stopColor='var(--fourth-color)'
            stopOpacity='{1}'
          ></stop>
        </linearGradient>
      </defs>
      <rect
        x='26.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#max)'
      ></rect>
      <rect
        x='36.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#max)'
      ></rect>
      <rect
        x='46.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#max)'
      ></rect>
      <rect
        x='56.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#max)'
      ></rect>
      <rect
        x='66.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#max)'
      ></rect>
      <rect
        x='76.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#max)'
      ></rect>
      <rect
        x='86.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#max)'
      ></rect>
      <rect
        x='96.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#max)'
      ></rect>
      <rect
        x='106.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#max)'
      ></rect>
    </svg>
  );
};

export const bidAsk = () => {
  return (
    <svg
      width='120'
      height='56'
      viewBox='0 0 142 56'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
    >
      <defs>
        <linearGradient id='bidAsk' x1='0' y1='0' x2='0' y2='1'>
          <stop
            offset='0%'
            stopColor='var(--third-color)'
            stopOpacity='{0}'
          ></stop>
          <stop
            offset='100%'
            stopColor='var(--fourth-color)'
            stopOpacity='{1}'
          ></stop>
        </linearGradient>
      </defs>
      <rect
        x='26.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#bidAsk)'
      ></rect>
      <rect
        opacity='0.8'
        x='36.5'
        y='16'
        width='9'
        height='32'
        rx='2'
        fill='url(#bidAsk)'
      ></rect>
      <rect
        opacity='0.6'
        x='46.5'
        y='24'
        width='9'
        height='24'
        rx='2'
        fill='url(#bidAsk)'
      ></rect>
      <rect
        opacity='0.4'
        x='56.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#bidAsk)'
      ></rect>
      <rect
        opacity='0.2'
        x='66.5'
        y='40'
        width='9'
        height='8'
        rx='2'
        fill='url(#bidAsk)'
      ></rect>
      <rect
        opacity='0.4'
        x='76.5'
        y='32'
        width='9'
        height='16'
        rx='2'
        fill='url(#bidAsk)'
      ></rect>
      <rect
        opacity='0.6'
        x='86.5'
        y='24'
        width='9'
        height='24'
        rx='2'
        fill='url(#bidAsk)'
      ></rect>
      <rect
        opacity='0.8'
        x='96.5'
        y='16'
        width='9'
        height='32'
        rx='2'
        fill='url(#bidAsk)'
      ></rect>
      <rect
        x='106.5'
        y='8'
        width='9'
        height='40'
        rx='2'
        fill='url(#bidAsk)'
      ></rect>
    </svg>
  );
};
